=== composestar/composestar/Core/Compiletime/src/Composestar/Core/TASMAN/Xml/TASMANConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://composestar.sourceforge.net/schema/TASMAN" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://composestar.sourceforge.net/schema/TASMAN">
    <xsd:annotation>
    	<xsd:documentation>
    		Configuration file for the task manager module (TASMAN) which is responsible for the execution of the
    		various modules.
    	</xsd:documentation>
    </xsd:annotation>

    <xsd:complexType name="TaskCollection">
    	<xsd:annotation>
    		<xsd:documentation>Defines a collection of tasks</xsd:documentation>
    	</xsd:annotation>
    	<xsd:choice maxOccurs="unbounded" minOccurs="1">
    		<xsd:group ref="TaskTypes"></xsd:group></xsd:choice>
    </xsd:complexType>
    
    <xsd:complexType name="ParallelTask">
    	<xsd:annotation>
    		<xsd:documentation>Tasks in this collection will be executed in parallel</xsd:documentation>
    	</xsd:annotation>
    	<xsd:complexContent>
    		<xsd:extension base="TaskCollection">
    			<xsd:attribute name="max" use="optional">
    				<xsd:annotation>
    					<xsd:documentation>
    						The maximum number of parallel running tasks. Defaults to the number of child tasks.
    					</xsd:documentation>
    				</xsd:annotation>
    				<xsd:simpleType>
    					<xsd:restriction base="xsd:int">
    						<xsd:whiteSpace value="collapse"></xsd:whiteSpace>
    						<xsd:minInclusive value="0"></xsd:minInclusive>
    					</xsd:restriction>
    				</xsd:simpleType>
    			</xsd:attribute>
    			<xsd:attribute name="perprocessor" use="optional">
    				<xsd:annotation>
    					<xsd:documentation>
    						The maximum number of tasks to be executed per available processor. This attribute will
    						override the value of the max attribute.
    					</xsd:documentation>
    				</xsd:annotation>
    				<xsd:simpleType>
    					<xsd:restriction base="xsd:int">

    						<xsd:minInclusive value="0"></xsd:minInclusive>

    						<xsd:whiteSpace value="collapse"></xsd:whiteSpace>
    					</xsd:restriction>
    				</xsd:simpleType>
    			</xsd:attribute>
    		</xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>

    <xsd:group name="TaskTypes">
    	<xsd:sequence>
    		<xsd:element name="sequential" type="TaskCollection"></xsd:element>
    		<xsd:element name="parallel" type="ParallelTask"></xsd:element>
    		<xsd:element name="module" type="ModuleTask"></xsd:element>
    	</xsd:sequence>
    </xsd:group>


    <xsd:element name="tasks" type="TaskCollection"></xsd:element>

    <xsd:complexType name="ModuleTask">
    	<xsd:annotation>
    		<xsd:documentation>A task that executes a specific module.</xsd:documentation>
    	</xsd:annotation>
    	<xsd:attribute name="class" type="xsd:string">
    		<xsd:annotation>
    			<xsd:documentation>The fully qualified name of the module to execute.</xsd:documentation>
    		</xsd:annotation></xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== composestar/composestar/CwC/Compiletime/src/TASMANConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasks xmlns="http://composestar.sourceforge.net/schema/TASMAN" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://composestar.sourceforge.net/schema/TASMAN ../../ComposestarCORE/src/Composestar/Core/TASMAN/Xml/TASMANConfig.xsd ">
	<module class="Composestar.Core.COPPER3.COPPER" />
	<module class="Composestar.Core.EMBEX.EMBEX" />
	<module class="Composestar.CwC.COMP.PreProcess" />
	<module class="Composestar.CwC.TYM.Harvester.TypeHarvester" />
	<module class="Composestar.CwC.TYM.Collector.LangModelConverter" />
	<module class="Composestar.Core.REXREF2.RexRef" />
	<module class="Composestar.CwC.LOLA.CwCLOLA" />
	<module class="Composestar.Core.CHKREP2.Check" />
	<module class="Composestar.Core.SANE2.Imposer" />
	<module class="Composestar.Core.FILTH2.FILTH" />
	<module class="Composestar.Core.DEPART.Departure" />
	<module class="Composestar.Core.FIRE2.preprocessing.Preprocessor" />
	<module class="Composestar.Core.CORE2.Core" />
	<module class="Composestar.Core.SIGN2.Sign" />
	<module class="Composestar.Core.DIGGER2.DIGGER" />
	<module class="Composestar.Core.INLINE.lowlevel.ModelBuilder" />
	<module class="Composestar.CwC.WEAVER.CwCWeaver" />
	<module class="Composestar.Core.SECRET3.SECRET" />
	<!-- CwC.LAMA is not very serializable <module class="Composestar.Core.INCRE.INCRESerializer" />-->
</tasks>

=== composestar/composestar/Java/Compiletime/src/TASMANConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasks xmlns="http://composestar.sourceforge.net/schema/TASMAN" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://composestar.sourceforge.net/schema/TASMAN ../../ComposestarCORE/src/Composestar/Core/TASMAN/Xml/TASMANConfig.xsd ">
	<module class="Composestar.Core.COPPER3.COPPER" />
	<module class="Composestar.Core.EMBEX.EMBEX" />
	<module class="Composestar.Core.DUMMER.DummyManager" />
	<module class="Composestar.Java.TYM.TypeHarvester.JavaHarvestRunner" />
	<module class="Composestar.Java.TYM.TypeCollector.JavaCollectorRunner" />
	<module class="Composestar.Java.TYM.TypeCollector.AnnotationCollector" />
	<module class="Composestar.Core.REXREF2.RexRef" />
	<module class="Composestar.Java.LOLA.JavaLOLA" />
	<!-- <module class="Composestar.Core.FITER.FITER" />  --><!-- disabled for now -->
	<parallel perprocessor="1">
		<module class="Composestar.Core.CHKREP2.Check" />
	</parallel>
	<module class="Composestar.Core.SANE2.Imposer" />
	<module class="Composestar.Core.FILTH2.FILTH" />
	<module class="Composestar.Core.DEPART.Departure" />
	<module class="Composestar.Core.FIRE2.preprocessing.Preprocessor" />
	<module class="Composestar.Core.CORE2.Core" />
	<module class="Composestar.Core.SIGN2.Sign" />
	<parallel perprocessor="1">
		<!-- 
		<module class="Composestar.Core.DIGGER2.DIGGER" />
		<module class="Composestar.Core.CKRET.CKRET" />
	 -->
		<sequential>
			<module class="Composestar.Java.TYM.SignatureTransformer.JavaSignatureTransformer" />
			<module class="Composestar.Core.RECOMA.RealSourceManager" />
			<module class="Composestar.Java.CONE.JavaRepositorySerializer" />
			<module class="Composestar.Java.WEAVER.JavaWeaver" />
			<module class="Composestar.Java.BACO.JavaBACO" />
		</sequential>
	</parallel>
	<!-- 
	<module class="Composestar.Core.INCRE.INCRESerializer" />
	 -->
</tasks>

=== composestar/composestar/StarLight/Source/Compiletime/src/TASMANConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasks xmlns="http://composestar.sourceforge.net/schema/TASMAN" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://composestar.sourceforge.net/schema/TASMAN ../../ComposestarCORE/src/Composestar/Core/TASMAN/Xml/TASMANConfig.xsd ">
	<module class="Composestar.DotNET2.TYM.RepositoryCollector.StarLightCollectorRunner" />
	<module class="Composestar.Core.COPPER3.COPPER" />
	<module class="Composestar.Core.REXREF.ParumREXREF" />
	<module class="Composestar.DotNET2.LOLA.DotNETLOLA" />
	<module class="Composestar.Core.REXREF.Main" />
	<module class="Composestar.Core.CHKREP2.Check" />
	<module class="Composestar.Core.SANE.SANE" />
	<module class="Composestar.Core.FILTH2.FILTH" />
	<module class="Composestar.Core.FIRE2.preprocessing.Preprocessor" />
	<module class="Composestar.Core.CORE2.Core" />
	<module class="Composestar.Core.SIGN2.Sign" />
	<module class="Composestar.Core.CKRET.CKRET" />
	<module class="Composestar.Core.INLINE.lowlevel.ModelBuilder" />
	<module class="Composestar.DotNET2.TYM.RepositoryEmitter.StarLightEmitterRunner" />
	<module class="Composestar.Core.INCRE.INCRESerializer" />
</tasks>

=== composestar/composestar/DotNET/Compiletime/src/TASMANConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasks xmlns="http://composestar.sourceforge.net/schema/TASMAN" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://composestar.sourceforge.net/schema/TASMAN ../../ComposestarCORE/src/Composestar/Core/TASMAN/Xml/TASMANConfig.xsd ">
	<module class="Composestar.Core.COPPER2.COPPER" />
	<module class="Composestar.Core.EMBEX.EMBEX" />
	<module class="Composestar.Core.DUMMER.DummyManager" />
	<module class="Composestar.DotNET.TYM.TypeHarvester.DotNETHarvestRunner" />
	<module class="Composestar.DotNET.TYM.TypeCollector.DotNETCollectorRunner" />
	<module class="Composestar.DotNET.TYM.TypeCollector.AttributeCollector" />
	<module class="Composestar.Core.REXREF.ParumREXREF" />
	<module class="Composestar.DotNET.LOLA.DotNETLOLA" />
	<module class="Composestar.Core.REXREF.Main" />
	<module class="Composestar.Core.FITER.FITER" />
	<module class="Composestar.Core.CHKREP2.Check" />
	<module class="Composestar.Core.SANE.SANE" />
	<module class="Composestar.Core.FILTH2.FILTH" />
	<module class="Composestar.Core.FIRE2.preprocessing.Preprocessor" />
	<module class="Composestar.Core.CORE2.Core" />
	<module class="Composestar.Core.SIGN2.Sign" />
	<module class="Composestar.Core.DIGGER2.DIGGER" />
	<module class="Composestar.DotNET.ASTRA.ASTRA" />
	<module class="Composestar.Core.RECOMA.RealSourceManager" />
	<module class="Composestar.DotNET.CONE.DotNETWeaveFileGenerator" />
	<module class="Composestar.DotNET.ILICIT.ILICIT" />
	<module class="Composestar.DotNET.SEMTEX.DotNETSemTexRunner" />
	<module class="Composestar.DotNET.SEMTEX.DotNETSemTexCollector" />
	<module class="Composestar.Core.CKRET.CKRET" />
	<module class="Composestar.DotNET.CONE.DotNETRepositorySerializer" />
	<module class="Composestar.DotNET.BACO.DotNETBACO" />
	<module class="Composestar.Core.INCRE.INCRESerializer" />
</tasks>
