=== composestar/composestar/Core/Compiletime/src/Composestar/Core/CKRET/Config/Xml/SecretConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://composestar.sourceforge.net/schema/SecretConfiguration"
	elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://composestar.sourceforge.net/schema/SecretConfiguration">
	<xsd:element name="secret">
		<xsd:annotation>
			<xsd:documentation>
				The entry element for the secret configuration. It contains a list of resource, rule and action
				declarations (in any order and multiplicity).
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded" minOccurs="0">
				<xsd:choice>
					<xsd:element name="resource" type="Resource"></xsd:element>
					<xsd:element name="rule" type="Rule"></xsd:element>
					<xsd:element name="action" type="Action"></xsd:element>
				</xsd:choice>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="Resource">
		<xsd:annotation>
			<xsd:documentation>Defines a resource and it's vocabulary.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="operation" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>
						A possible operation on this resource. A warning will be issues when a operation is used on an
						resource which has not be defined previously.
					</xsd:documentation>
				</xsd:annotation>
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value="[A-Za-z][A-Za-z0-9]*"></xsd:pattern>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" use="required">
			<xsd:annotation>
				<xsd:documentation>
					The name of the resource. There are a few predefined names: message (a.k.a. msg), target, selector,
					return, arg, args. Any other name will be considered a custom resource.
				</xsd:documentation>
			</xsd:annotation>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:pattern value="[A-Za-z][A-Za-z0-9]*"></xsd:pattern>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="override" type="xsd:boolean" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					If set to true it will replace the previous definition. Otherwise it will simply append the
					vocabulary.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>

	</xsd:complexType>

	<xsd:complexType name="Rule">
		<xsd:annotation>
			<xsd:documentation>Defines a conflict rule.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="pattern" maxOccurs="1" minOccurs="1">
				<xsd:annotation>
					<xsd:documentation>
						The regular expression pattern for this rule. This pattern will be applied to a string of
						operations. Only a subset of regular expressions have been implemented. The regular expression
						only works on words and not individual characters. For this reason expressions like "ab*c" are
						not allowed. Use: "a(b)*c". Multipliers are only allowed on subexpresions and the dot wildcard:
						.* and .+ are allowed, a single dot is not allowed. A sequence of operations is defined as:
						"(read)(write)(read)". Alternatives can be defined using the pipe "|": "read|write" or
						"(read)|(write)". The zero-width negative lookahead is also aprtially supported, sequences are
						not allowed. To match all but read or write: "(?!read|write)" or
						"(foo)bar(?!read|write|encrypt)foo"
					</xsd:documentation>
				</xsd:annotation>
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
						<xsd:whiteSpace value="collapse"></xsd:whiteSpace>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="message" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>A message to show when this rule is violated.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="scope" maxOccurs="unbounded" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						Defines a scope to which this rule applies. Without a single scope definition this rule will
						apply to all sequences.
					</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:annotation>
						<xsd:documentation>
							Defines a scope. A scope consists of a scope type and the name of the object to match with.
						</xsd:documentation>
					</xsd:annotation>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attribute name="type">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:enumeration value="class"></xsd:enumeration>
										<xsd:enumeration value="method"></xsd:enumeration>
										<xsd:enumeration value="filter"></xsd:enumeration>
										<xsd:enumeration value="filteraction"></xsd:enumeration>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:attribute>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>

		</xsd:sequence>
		<xsd:attribute name="resource" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation>The resource this rule applies to.</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="type">
			<xsd:annotation>
				<xsd:documentation>
					The type of rule, either a constraint (must not match) or an assertion (must match).
				</xsd:documentation>
			</xsd:annotation>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="constraint"></xsd:enumeration>
					<xsd:enumeration value="assertion"></xsd:enumeration>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="Action">
		<xsd:annotation>
			<xsd:documentation>
				Defines a series of resource operations applied at a given execution model transitions.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="label" maxOccurs="unbounded" minOccurs="1">
				<xsd:annotation>
					<xsd:documentation>One or more labels for which this action sequence applies</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attribute name="type" use="required">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:enumeration value="transition"></xsd:enumeration>
										<xsd:enumeration value="node"></xsd:enumeration>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:attribute>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="sequence" maxOccurs="unbounded" minOccurs="1">
				<xsd:annotation>
					<xsd:documentation>A sequence of operations applied to the given resource</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attribute name="resource" type="xsd:string" use="required">
								<xsd:annotation>
									<xsd:documentation>
										The name of the resource this sequence applies to.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:attribute>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>

		</xsd:sequence>

		<xsd:attribute name="priority" type="xsd:int"></xsd:attribute>
	</xsd:complexType>
</xsd:schema>

=== composestar/composestar/Core/Compiletime/src/Composestar/Core/CKRET/SECRETConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<secret xmlns="http://composestar.sourceforge.net/schema/SecretConfiguration"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://composestar.sourceforge.net/schema/SecretConfiguration Config/SecretConfiguration.xsd ">

	<resource name="message">
		<operation>discard</operation>
		<operation>dispatch</operation>
		<operation>exit</operation>
		<operation>return</operation>
	</resource>
	<resource name="target">
		<operation>read</operation>
		<operation>write</operation>
	</resource>
	<resource name="selector">
		<operation>read</operation>
		<operation>write</operation>
	</resource>
	<resource name="return">
		<operation>discard</operation>
		<operation>read</operation>
		<operation>write</operation>
	</resource>
	<resource name="arg">
		<operation>discard</operation>
		<operation>read</operation>
		<operation>write</operation>
	</resource>
	
	<action priority="-100">
		<!-- Matching part, always happens before a filter action can do anything -->
		<label type="transition"><![CDATA[<NameMatchingPart-any-false>]]></label>
		<label type="transition"><![CDATA[<NameMatchingPart-false-star>]]></label>
		<label type="transition"><![CDATA[<NameMatchingPart-false-true>]]></label>
		<label type="transition"><![CDATA[<NameMatchingPart-star-star>]]></label>
		<label type="transition"><![CDATA[<NameMatchingPart-star-true>]]></label>
		<label type="transition"><![CDATA[<NameMatchingPart-true-star>]]></label>
		<label type="transition"><![CDATA[<NameMatchingPart-true-true>]]></label>
		<label type="transition"><![CDATA[<SignatureMatchingPart-false>]]></label>
		<label type="transition"><![CDATA[<SignatureMatchingPart-true-star>]]></label>
		<label type="transition"><![CDATA[<SignatureMatchingPart-true-true>]]></label>
		<sequence resource="target">read</sequence>
		<sequence resource="selector">read</sequence>
	</action>
	
	<action priority="-1">
		<!-- Message substitution happens before the execution of a filter action -->
		<label type="node"><![CDATA[SubstitutedMessageAction]]></label>
		<sequence resource="target">write</sequence>
		<sequence resource="selector">write</sequence>
	</action>
	
	<action priority="1">
		<!-- The flow is changed after the filter execution -->
		<label type="node"><![CDATA[ReturnFlowAction]]></label>
		<sequence resource="message">return</sequence>
	</action>
	
	<action priority="1">
		<!-- The flow is changed after the filter execution -->
		<label type="node"><![CDATA[ExitFlowAction]]></label>
		<sequence resource="message">exit</sequence>
	</action>
	
		
	<rule resource="message" type="constraint">
		<pattern>(exit)(return|dispatch)</pattern>
		<message>Can not return or dispatch a message after an exit.</message>
	</rule>
	
	<rule resource="message" type="constraint">
		<pattern>(return)(return)</pattern>
		<message>A message can be returned only once.</message>
	</rule>
	
	<rule resource="*" type="constraint">
		<pattern>(discard)![exit]+</pattern><!-- exit is allowed for message -->
		<message>Discarded resources can not be accessed.</message>
	</rule>
</secret>
